theme: minima
#minima:
  #skin: classic
  #skin: dark
title: APAC TIP Program
description: Explore electronics tinkering, my latest DIY projects and shooting sports.
show_excerpts: true
plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
#  - jekyll-sitemap
social_links:
    - { platform: facebook,       user_url: "https://www.facebook.com/leru" }
    - { platform: github,         user_url: "https://github.com/janleroux" }
    - { platform: instagram,      user_url: "https://www.instagram.com/leru_io" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/janleroux" }
