theme: minima
#minima:
  #skin: classic
  #skin: dark
title: Tinker-and-Target
description: Explore electronics tinkering, my latest DIY projects and shooting sports.
show_excerpts: true
#social_links:
#    - { platform: facebook,       user_url: "https://www.facebook.com/leru" }
#    - { platform: github,         user_url: "https://github.com/janleroux" }
#    - { platform: instagram,      user_url: "https://www.instagram.com/leru_io" }
#    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/janleroux" }
